import { RecommendResponse } from '../types';

// Centered on San Francisco — swap for your test location
export const MOCK_LOCATION = { latitude: 37.7749, longitude: -122.4194 };

export const MOCK_RESPONSE: RecommendResponse = {
  best_station: {
    name: 'Valero',
    address: '2599 Mission St, San Francisco, CA',
    latitude: 37.7526,
    longitude: -122.4186,
    price_per_gallon: 4.09,
    distance_miles: 1.61,
    drive_time_minutes: 6.2,
    effective_cost: 35.48,
    gallons_purchased: 8.675,
    fuel_burned_in_transit: 0.175,
    rank: 1,
    savings_vs_best: 0.0,
    reachable: true,
  },
  all_stations: [
    {
      name: 'Valero',
      address: '2599 Mission St, San Francisco, CA',
      latitude: 37.7526,
      longitude: -122.4186,
      price_per_gallon: 4.09,
      distance_miles: 1.61,
      drive_time_minutes: 6.2,
      effective_cost: 35.48,
      gallons_purchased: 8.675,
      fuel_burned_in_transit: 0.175,
      rank: 1,
      savings_vs_best: 0.0,
      reachable: true,
    },
    {
      name: 'Arco',
      address: '800 Bryant St, San Francisco, CA',
      latitude: 37.7753,
      longitude: -122.4033,
      price_per_gallon: 4.15,
      distance_miles: 0.9,
      drive_time_minutes: 3.8,
      effective_cost: 35.76,
      gallons_purchased: 8.632,
      fuel_burned_in_transit: 0.132,
      rank: 2,
      savings_vs_best: -0.28,
      reachable: true,
    },
    {
      name: 'Chevron',
      address: '100 Market St, San Francisco, CA',
      latitude: 37.7935,
      longitude: -122.3964,
      price_per_gallon: 4.29,
      distance_miles: 2.14,
      drive_time_minutes: 9.1,
      effective_cost: 37.04,
      gallons_purchased: 8.576,
      fuel_burned_in_transit: 0.076,
      rank: 3,
      savings_vs_best: -1.56,
      reachable: true,
    },
    {
      name: '76',
      address: '1 Cesar Chavez St, San Francisco, CA',
      latitude: 37.7488,
      longitude: -122.4062,
      price_per_gallon: 4.35,
      distance_miles: 3.08,
      drive_time_minutes: 12.4,
      effective_cost: 37.59,
      gallons_purchased: 9.0,
      fuel_burned_in_transit: 0.11,
      rank: 4,
      savings_vs_best: -2.11,
      reachable: true,
    },
    {
      name: 'Shell',
      address: '200 Mission St, San Francisco, CA',
      latitude: 37.7885,
      longitude: -122.3994,
      price_per_gallon: 4.41,
      distance_miles: 1.43,
      drive_time_minutes: 6.0,
      effective_cost: 38.16,
      gallons_purchased: 8.551,
      fuel_burned_in_transit: 0.051,
      rank: 5,
      savings_vs_best: -2.68,
      reachable: true,
    },
  ],
  note: 'Valero saves $0.28 vs Arco with a $0.06/gal lower price.',
  region_avg_price: 4.26,
  city: 'San Francisco',
  state: 'CA',
  tank_is_full: false,
};
